### ISSUE TITLE
Hey README.md is missing

### ISSUE THREAD

**Issue by perenecabuto** [karma-runner/karma-ng-html2js-preprocessor#47]
I am getting an annoying warning that I do not think I deserve.
npm WARN package.json karma-ng-html2js-preprocessor@0.1.1 No README data

Please fix it. =D
Regards.

**Comment by Dignifiedquire** [comment]
Fixed when I'm looking at `0.1.2` on npm: https://www.npmjs.com/package/karma-ng-html2js-preprocessor
