### ISSUE TITLE
Can't inject it into my test?

### ISSUE THREAD

**Issue by moneytree-doug** [karma-runner/karma-ng-html2js-preprocessor#59]
I have tried many different combinations, but I don't understand why this isn't being instantiated. Could I get some help?
```
Error: [$injector:modulerr] Failed to instantiate module templates due to:
Error: [$injector:nomod] Module 'templates' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
````

karma.conf.js:

```
    files: [
      // if you wanna load template files in nested directories, you must use this
      '**/*.html'
    ],

    preprocessors: { 'app/views/**/*.html': 'html2js' },

    ngHtml2JsPreprocessor: {
      // setting this option will create only a single module that contains templates
      // from all the files, so you can load them all with module('foo')
      moduleName: 'templates'
    },

```

```
beforeEach(module('templates'));
```

**Comment by maksimr** [comment]
@moneytree-doug 

1. change `html2js`(it's deprecated) on `ng-html2js`
2. Do you have html files in `app/views/`?

**Comment by moneytree-doug** [comment]
@maksimr Ahh, I see. Yes I do have a ``app/views`` folder with tons of HTML files in it. I am trying to get this to work, so I don't have to use a passthrough in all of my tests. I tried changing it to ng-html2js just now, but still have an issue with the templates module not existing. Do you have an idea of why else it might now be working?

**Comment by moneytree-doug** [comment]
First thing I found out here is that you need to add this as a plugin to karma which is completely undocumented, and there is even a PR for it #60. This could have saved me some time, but I am still experiencing the same issue.

**Comment by moneytree-doug** [comment]
Okay, so after I found out that I needed to add it as a plugin, I was able to run the karma test with debug to see what was processing. Afterwards, I removed ``../..` from all my states for Angular app. After this, I had the following karma.conf for the ngHtml2JsPreprocessor:

```
    ngHtml2JsPreprocessor: {
      stripPrefix: 'app/',
      prependPrefix: '/',
      moduleName: 'templates'
    },
```

Got it working, hopefully this will help someone else in the future.

**Comment by pkozlowski-opensource** [comment]
Glad you've got it resolved @moneytree-doug

**Comment by SirRagnar** [comment]
@moneytree-doug thanks for post your self resolution. It has helped to me.
