### ISSUE TITLE
Doesn't work in strictDi mode

### ISSUE THREAD

**Issue by scottohara** [karma-runner/karma-ng-html2js-preprocessor#62]
In my angular 1.3 apps, I always use the new `ng-strict-di` directive on my `ng-app`, to help detect any dependencies that aren't properly annotated (and would break when minified), eg.
```
<html ng-app="myApp" ng-strict-di>
```

In addition, my test suite has a `beforeEach()` block outside of any `describe()` (meaning that it runs before every spec), that enables `strictDi` mode, eg.
```
beforeEach(inject.strictDi(true));
```

This causes a problem when loading any templates processed into modules by ng-html2js, eg.
```
beforeEach(module("path/to/template.html"));
```

They fail with the error:
```
Error: [$injector:strictdi] function($templateCache) is not using explicit annotation and cannot be invoked in strict mode
```

The problem appears to be that module code generated by ng-html2js does not use explicit annotation style for the injected $templateCache dependency, ie.
```
var TEMPLATE = 'angular.module(\'%s\', []).run(function($templateCache) {\n' +
    '  $templateCache.put(\'%s\',\n    \'%s\');\n' +
    '});\n';
```

Although it's unlikely that test code would ever be minified (so I can understand why annotations weren't used), could I suggest properly annotating the dependencies anyway;  as this will enable `strictDi` mode to be enabled globally.

The proposed change would be something like:
```
var TEMPLATE = 'angular.module(\'%s\', []).run(["$templateCache", function($templateCache) {\n' +
    '  $templateCache.put(\'%s\',\n    \'%s\');\n' +
    '}]);\n';
```

**Comment by pkozlowski-opensource** [comment]
I think that this is very reasonable proposal. Would you fancy sending us a PR?
