### ISSUE TITLE
missing plugin error

### ISSUE THREAD

**Issue by yccteam** [karma-runner/karma-ng-html2js-preprocessor#66]
Hi,
I got a working jasmine-karma, and just installed this after reading: https://docs.angularjs.org/guide/unit-testing, which directes here.
So I installed the plugin and setup the karma.conf.js as mentioned in the readme file.
When I run Karma I get:
```Cannot load ng-html2js, it is not registered
Perhaps you are missing some plugin?```

Any idea why this happens?

**Comment by chatchavan** [comment]
In your `karma.conf.js`, add `'karma-ng-html2js-preprocessor',` to the `plugins`.

**Comment by yccteam** [comment]
Hi,
It was the first or second thing I tried - with no success...
It just says the same thing about "plugins" instead of "preprocessors" (```WARN ["plugins"]```).
requirejs and jasmin do work though...
Any more ideas?

**Comment by chatchavan** [comment]
Just a sanity check, you already installed the package by `npm install --save-dev karma-ng-html2js-preprocessor`, right?

**Comment by yccteam** [comment]
Hmmm... I've installed it globally. 
My Karma is installed globally, so that's what I did with this plugin...
Might this be the issue?

**Comment by pkozlowski-opensource** [comment]
It needs to be installed locally

**Comment by yccteam** [comment]
Sorry about that... I've just copied the files locally and it reads the plugin :)
