### ISSUE TITLE
Config instructions missing the bit about adding to plugins

### ISSUE THREAD

**Issue by jeanrnewyyz** [karma-runner/karma-ng-html2js-preprocessor#70]
Not knowing how everything is connected, I spent a lot of time before realizing that I needed to add this modules to karma config plugins for it to work:

config.set({
...,
plugins: [
      ...,
      'karma-ng-html2js-preprocessor'
    ],
...
});

!!

**Comment by pkozlowski-opensource** [comment]
This is documented here: http://karma-runner.github.io/0.12/config/plugins.html

Normally you do _not_ need to specify plugins manually in the `plugins` section - unless you start adding things "by hand"....

**Comment by jeanrnewyyz** [comment]
Well, I definitely used

npm install karma-ng-html2js-preprocessor --save-dev

and it ng-html2js was not seen as "registered" in when executing "karma
start karma.conf.js" until I manually added it to plugins: {}.

More info is better than not enough, IMO.  Otherwise, while I'm trying to
fix my problem, I have to google for hours because of the granularity of
the docs.

Thanks all the same for a very useful modules.


Jean



--
*Jean Rajotte - Consultant*
*New Toronto Group*
4 Robert Speck Parkway, Suite 240
Mississauga, ON, Canada L4Z 1S1
P: 647.525.4836
F: 905.897.9952
*jeanr@newyyz.com* <jeanr@newyyz.com>
www.newyyz.com
