### ISSUE TITLE
Need version bump

### ISSUE THREAD

**Issue by nephiw** [karma-runner/karma-ng-html2js-preprocessor#80]
I am trying to use the configuration where you pass a function to moduleName. I have verified that I am using the most recent version number and I am installing via npm. But instead of calling my method, it uses the function definition as the module name - obviously this doesn't work.

It looks like the code is implemented, but the version number has not been bumped up. When can I expect the version bump?

**Comment by jcharters** [comment]
I have also encountered this problem, it would be great to have a version bump ASAP. 

Our CI environment (TeamCity) naturally performs a NPM install on each build, and this results in the older library code being set up. Our current workaround is to bring the current GitHub code into our project so we can use this feature -- nasty but works for now.

**Comment by Dignifiedquire** [comment]
Just published `0.2.0` which should have everything in it.
