### ISSUE TITLE
Can't find variable when using jspm

### ISSUE THREAD

**Issue by micaelmbagira** [karma-runner/karma-ng-html2js-preprocessor#91]
I'm using **jspm** to load angular, when I run karma, I have `Can't find variable: angular`. This error is generated by the file generated by `ng-html2js`.
Here is my karma.conf :

````js
module.exports = function (config) {
  const configuration = {
    browsers: [
      'PhantomJS'
    ],
    basePath: '../',
    singleRun: true,
    autoWatch: false,
    logLevel: 'INFO',
    junitReporter: {
      outputDir: 'test-reports'
    },
    frameworks: [
      'phantomjs-shim',
      'jspm',
      'jasmine'
    ],
    preprocessors: {
      [conf.path.src('**/*.html')]: [
        'ng-html2js'
      ]
    },
    ngHtml2JsPreprocessor: {},
    jspm: {
      config: 'jspm.config.js',
      loadFiles: [
        conf.path.src('app/**/*.js'),
        conf.path.src('**/*.html')
      ]
    },
    plugins: [
      require('karma-jasmine'),
      require('karma-junit-reporter'),
      require('karma-phantomjs-launcher'),
      require('karma-phantomjs-shim'),
      require('karma-coverage'),
      require('karma-ng-html2js-preprocessor'),
      require('karma-jspm')
    ]
  };

  config.set(configuration);
};
````
I tried to add `angular` to the paths lists and also to the files list but none worked.

**Comment by sylvaindumont** [comment]
The only workaround i've found is to add angular to the files list

```
    files: [
      'jspm_packages/github/angular/bower-angular@1.5.3/angular.js',
      'client/app/**/*.html'
    ],
```

But it produce `'WARNING: Tried to load angular more than once.'` and will break at each new angular version.

**Comment by micaelmbagira** [comment]
Well it doesn't work for me... here is a replication project you can easily clone https://github.com/micaelmbagira/karma-jspm-replication
I've added `angular.js` to files list but still getting the same error.

**Comment by sylvaindumont** [comment]
You need to install the exact installed version, you have angular 1.5.0 in your package.json
```
"jspm": {
    "dependencies": {
      "angular": "npm:angular@^1.5.0",
      "babel": "npm:babel-core@^6.6.5"
    },
```
and angular 1.5.3 in your karma config
```
 files: [
      'jspm_packages/npm/angular/angular@1.5.3/angular.js'
    ],
```
If you have `jspm install` before the release of 1.5.3, the version mismatch.

**Comment by micaelmbagira** [comment]
No, I have `^1.5.0` which gets `angular@1.5.3` (cf http://semver.npmjs.com/)

**Comment by sylvaindumont** [comment]
yep, but with the next release of angular, you'll have a mismatch again between 1.5.3 and 1.5.4, you have to freeze the version with  `"angular": "npm:angular@=1.5.3"`

**Comment by sylvaindumont** [comment]
The last diff with my config is that I use : 
`'jspm_packages/github/angular/bower-angular@1.5.3/angular.js',`
and you use : 
`'jspm_packages/npm/angular/angular@1.5.3/angular.js'`
but it shouldn't make a difference;

**Comment by micaelmbagira** [comment]
Yes sure, I am aware about the version update problem
